CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  discordId VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT,
  womId VARCHAR(255) NOT NULL UNIQUE,
  womUsername VARCHAR(255) NOT NULL,
  isMain BOOLEAN NOT NULL,
  inClan BOOLEAN NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE ClanActivityLogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT,
  description VARCHAR(255) NOT NULL,
  points INT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id)
);